services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass
      POSTGRES_MULTIPLE_DATABASES: nightout_recommender_db,db2
    volumes:
      - ./init_databases.sh:/docker-entrypoint-initdb.d/init_databases.sh
    ports:
      - 5432:5432
    restart: unless-stopped