services:
  main_system:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: guts-system
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=nightout_recommender_db
      - DB_USER=db_user
      - DB_PASSWORD=db_pass
      - SECRET_KEY=TMT6RPsWdLTAcSYdMSvAihU3FKxOtBPugB8F0DpgygIA2iqNlsImDoUIzPcxp
    restart: unless-stopped
    networks:
      default:
        aliases:
          - guts-system

networks:
  default:
    name: nginx_proxy
    external: true
